/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import ClasseDAO.HospedagemDAO;
import Classes.Hospedagem;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author francimar
 */
public class telaPesquisaReserva extends javax.swing.JFrame {

    private HospedagemDAO hosDAO;
    private Hospedagem hosp;
    private ResultSet rs;
    private int idHospedagem;

    public telaPesquisaReserva() throws ClassNotFoundException {
        initComponents();
        hosDAO = new HospedagemDAO();
        hosp = new Hospedagem();
        this.setLocationRelativeTo(null);

    }

    public void pesquisarReserva() throws SQLException {
        int x = 0;
        rs = hosDAO.pesquisarReserva(ftCpf.getText());
        //JOptionPane.showMessageDialog(null,rs.next());
        while (rs.next()){
            x = 1;
            idHospedagem = rs.getInt("id_hospedagem");
            DefaultTableModel dtmQuartos = (DefaultTableModel) tlbPesquisaReserva.getModel();
            dtmQuartos.addRow(new Object[]{rs.getString("nome"), rs.getDate("data_entrada"),
                rs.getDate("data_saida"), rs.getString("numero"), rs.getString(13),rs.getString(3)});
        }
        if (x == 0) {
            JOptionPane.showMessageDialog(null, "Nenhuma reserva encontrada!");
        }
    }

    public void montarTela() throws ClassNotFoundException, ParseException, SQLException {   
               
        int linha = tlbPesquisaReserva.getSelectedRow();
        hosp.setCpf(tlbPesquisaReserva.getModel().getValueAt(linha,5).toString());
        String data = tlbPesquisaReserva.getModel().getValueAt(linha,1).toString();        
        data = converterNoFormatobrasil(data);        
        hosp.setDataEntrada(converterData(data));
        hosp = hosDAO.pesquisar(hosp);  
        hosp.setId(idHospedagem);
        telaHospedagem tHosp = new telaHospedagem(hosp);
        tHosp.setVisible(true);
    }
    
    public String converterNoFormatobrasil(String data){
    
        //2015-05-25
        String ano = data.substring(0,4);
        String mes = data.substring(5, 7);
        String dia = data.substring(8, 10);
        //JOptionPane.showMessageDialog(null,"" + dia + "/" + mes + "/" + ano);
        String dataBrasil = dia + "/" + mes + "/" + ano;
        return dataBrasil;
    }
    
    public Date converterData(String data) throws ParseException{
    
        DateFormat formate = new SimpleDateFormat("dd/MM/yyyy");
        return (java.util.Date) formate.parse(data);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ftCpf = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlbPesquisaReserva = new javax.swing.JTable();
        jBFechar = new javax.swing.JButton();
        jBpesquisa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar Reservas");

        jLabel1.setText("CPF: ");

        try {
            ftCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tlbPesquisaReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data de Entrada", "Data Saída", "Nº do Quarto", "Categoria do Quarto", "cpf"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tlbPesquisaReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlbPesquisaReservaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tlbPesquisaReserva);

        jBFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancel.png"))); // NOI18N
        jBFechar.setText("Fechar");
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });

        jBpesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/zoom.png"))); // NOI18N
        jBpesquisa.setText("Pesquisa");
        jBpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBpesquisa))
                    .addComponent(jBFechar))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ftCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBpesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBFechar)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisaActionPerformed

        try {
            pesquisarReserva();
        } catch (SQLException ex) {
            Logger.getLogger(telaPesquisaReserva.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBpesquisaActionPerformed

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharActionPerformed

        dispose();

    }//GEN-LAST:event_jBFecharActionPerformed

    private void tlbPesquisaReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlbPesquisaReservaMouseClicked

        try {
            montarTela();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(telaPesquisaReserva.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(telaPesquisaReserva.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(telaPesquisaReserva.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tlbPesquisaReservaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPesquisaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPesquisaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPesquisaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPesquisaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new telaPesquisaReserva().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(telaPesquisaReserva.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ftCpf;
    private javax.swing.JButton jBFechar;
    private javax.swing.JButton jBpesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tlbPesquisaReserva;
    // End of variables declaration//GEN-END:variables
}
